apiVersion: v1
kind: Service
metadata:
    name: api-desafio-svc
spec:
    type: NodePort
    selector:
        app: api-desafio-pod
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
